import {
	IoLogoReact,
	IoLogoHtml5,
	IoLogoCss3,
	IoLogoJavascript,
	IoLogoSass,
	IoLogoGithub,
	IoLogoVue,
	IoLogoNodejs,
	IoLogoPython,
	IoLogoAngular,
	IoLogoWordpress,
} from "react-icons/io5";
import {
	SiNextdotjs,
	SiTailwindcss,
	SiTypescript,
	SiExpress,
	SiPhp,
	SiCsharp,
	SiLit,
} from "react-icons/si";

export default [
	{
		name: "HTML5",
		nameColor: "white",
		bg: "#FF5733",
		icon: <IoLogoHtml5 />,
		iconColor: "white",
		gradientFrom: "#FF5733",
		levelPercent: 100,
	},
	{
		name: "CSS3",
		nameColor: "white",
		bg: "#2196f3",
		icon: <IoLogoCss3 />,
		iconColor: "white",
		gradientFrom: "#2196f3",
		levelPercent: 90,
	},
	{
		name: "Tailwind",
		nameColor: "white",
		bg: "#0bb6d4",
		icon: <SiTailwindcss />,
		iconColor: "white",
		gradientFrom: "#0bb6d4",
		gradientTo: "#1dc9b9",
		levelPercent: 100,
	},
	{
		name: "Sass",
		nameColor: "white",
		bg: "#cf649a",
		icon: <IoLogoSass />,
		iconColor: "white",
		gradientFrom: "#cf649a",
		levelPercent: 80,
	},
	{
		name: "Javascript",
		nameColor: "white",
		bg: "#ebc917",
		icon: <IoLogoJavascript />,
		iconColor: "white",
		gradientFrom: "#ebc917",
		levelPercent: 85,
	},
	{
		name: "React",
		nameColor: "white",
		bg: "#222222",
		icon: <IoLogoReact />,
		iconColor: "#03d9fe",
		gradientFrom: "#03d9fe",
		levelPercent: 80,
	},
	{
		name: "Next.js",
		nameColor: "black",
		bg: "#ffffff",
		icon: <SiNextdotjs />,
		iconColor: "black",
		gradientFrom: "#ffffff",
		levelPercent: 70,
		outlined: true,
	},
	{
		name: "Typescript",
		nameColor: "white",
		bg: "#3178c6",
		icon: <SiTypescript />,
		iconColor: "white",
		gradientFrom: "#3178c6",
		levelPercent: 65,
	},
	{
		name: "Github",
		nameColor: "white",
		bg: "#000000",
		icon: <IoLogoGithub />,
		iconColor: "white",
		gradientFrom: "#000000",
		levelPercent: 80,
	},
	{
		name: "Vue",
		nameColor: "#41b783",
		bg: "#34495e",
		icon: <IoLogoVue />,
		iconColor: "#41b783",
		gradientFrom: "#41b783",
		levelPercent: 50,
	},
	{
		name: "Express",
		nameColor: "white",
		bg: "#353535",
		icon: <SiExpress />,
		iconColor: "white",
		gradientFrom: "#353535",
		levelPercent: 30,
	},
	{
		name: "Node",
		nameColor: "#333333",
		bg: "#689f63",
		icon: <IoLogoNodejs />,
		iconColor: "#333333",
		gradientFrom: "#689f63",
		levelPercent: 35,
	},
	{
		name: "Php",
		nameColor: "white",
		bg: "#9867d3",
		icon: <SiPhp />,
		iconColor: "white",
		gradientFrom: "#9867d3",
		levelPercent: 60,
	},
	{
		name: "Python",
		nameColor: "#ffd241",
		bg: "#3674a5",
		icon: <IoLogoPython />,
		iconColor: "#ffd241",
		gradientFrom: "#ffd241",
		levelPercent: 30,
	},
	{
		name: "Angular",
		nameColor: "white",
		bg: "#de0031",
		icon: <IoLogoAngular />,
		iconColor: "white",
		gradientFrom: "#c40030",
		gradientTo: "#de0031",
		levelPercent: 50,
	},
	{
		name: "C Sharp",
		nameColor: "white",
		bg: "#380191",
		icon: <SiCsharp />,
		iconColor: "white",
		gradientFrom: "#280065",
		gradientTo: "#380191",
		levelPercent: 40,
	},
	{
		name: "Wordpress",
		nameColor: "white",
		bg: "#00769c",
		icon: <IoLogoWordpress />,
		iconColor: "white",
		gradientFrom: "#00769c",
		levelPercent: 60,
	},
	{
		name: "LitElement",
		nameColor: "#2a2f9b",
		bg: "#00e8ff",
		icon: <SiLit />,
		iconColor: "#2a2f9b",
		gradientFrom: "#00e8ff",
		levelPercent: 70,
	},
];
