import {
	IoLogoReact,
	IoLogoHtml5,
	IoLogoCss3,
	IoLogoJavascript,
	IoLogoSass,
	IoLogoGithub,
	IoLogoVue,
	IoLogoNodejs,
	IoLogoPython,
	IoLogoAngular,
	IoLogoWordpress,
} from "react-icons/io5";
import {
	SiNextdotjs,
	SiTailwindcss,
	SiTypescript,
	SiExpress,
	SiPhp,
	SiCsharp,
	SiLit,
	SiMongodb,
	SiAdobephotoshop,
	SiUnity,
} from "react-icons/si";

const skills = [
	{
		name: "HTML5",
		nameColor: "white",
		bg: "#FF5733",
		icon: <IoLogoHtml5 />,
		iconColor: "white",
	},
	{
		name: "CSS3",
		nameColor: "white",
		bg: "#2196f3",
		icon: <IoLogoCss3 />,
		iconColor: "white",
	},
	{
		name: "Tailwind",
		nameColor: "white",
		bg: "#0bb6d4",
		icon: <SiTailwindcss />,
		iconColor: "white",
	},
	{
		name: "Sass",
		nameColor: "white",
		bg: "#cf649a",
		icon: <IoLogoSass />,
		iconColor: "white",
	},
	{
		name: "Javascript",
		nameColor: "white",
		bg: "#ebc917",
		icon: <IoLogoJavascript />,
		iconColor: "white",
	},
	{
		name: "React",
		nameColor: "white",
		bg: "#222222",
		icon: <IoLogoReact />,
		iconColor: "#03d9fe",
	},
	{
		name: "Next",
		nameColor: "black",
		bg: "#ffffff",
		icon: <SiNextdotjs />,
		iconColor: "black",
		outlined: true,
	},
	{
		name: "Typescript",
		nameColor: "white",
		bg: "#3178c6",
		icon: <SiTypescript />,
		iconColor: "white",
	},
	{
		name: "Github",
		nameColor: "white",
		bg: "#000000",
		icon: <IoLogoGithub />,
		iconColor: "white",
	},
	{
		name: "Vue",
		nameColor: "#41b783",
		bg: "#34495e",
		icon: <IoLogoVue />,
		iconColor: "#41b783",
	},
	{
		name: "Express",
		nameColor: "white",
		bg: "#353535",
		icon: <SiExpress />,
		iconColor: "white",
	},
	{
		name: "Node",
		nameColor: "#333333",
		bg: "#689f63",
		icon: <IoLogoNodejs />,
		iconColor: "#333333",
	},
	{
		name: "Php",
		nameColor: "white",
		bg: "#9867d3",
		icon: <SiPhp />,
		iconColor: "white",
	},
	{
		name: "Python",
		nameColor: "#ffd241",
		bg: "#3674a5",
		icon: <IoLogoPython />,
		iconColor: "#ffd241",
	},
	{
		name: "Angular",
		nameColor: "white",
		bg: "#de0031",
		icon: <IoLogoAngular />,
		iconColor: "white",
	},
	{
		name: "C Sharp",
		nameColor: "white",
		bg: "#380191",
		icon: <SiCsharp />,
		iconColor: "white",
	},
	{
		name: "Wordpress",
		nameColor: "white",
		bg: "#00769c",
		icon: <IoLogoWordpress />,
		iconColor: "white",
	},
	{
		name: "LitElement",
		nameColor: "#2a2f9b",
		bg: "#00e8ff",
		icon: <SiLit />,
		iconColor: "#2a2f9b",
	},
	{
		name: "MongoDB",
		nameColor: "#01ed66",
		bg: "#011e2c",
		icon: <SiMongodb />,
		iconColor: "#01ed66",
	},
	{
		name: "Photoshop",
		nameColor: "#2fa8ff",
		bg: "#001e36",
		icon: <SiAdobephotoshop />,
		iconColor: "#2fa8ff",
	},
	{
		name: "Unity",
		nameColor: "#000000",
		bg: "#ffffff",
		icon: <SiUnity />,
		iconColor: "#000000",
		outlined: true,
	},
];

export default skills;
