import Head from "next/head";
import Post from "../components/Post";
import { createClient } from "next-sanity";
import Searchbar from "../components/Searchbar";
import FilterChoice from "../components/Filters/FilterChoice";
import { useEffect, useState } from "react";
import { AnimatePresence } from "framer-motion";

const Blog = ({ posts }) => {
	const [activeChoices, setActiveChoices] = useState([]);
	const [allTags, setAllTags] = useState([]);

	useEffect(() => {
		if (posts) {
			let updatedTags = allTags.length ? allTags : [];
			posts.forEach(post => {
				if (post.tags) {
					post.tags.forEach(tag => {
						if (!allTags.includes(tag)) updatedTags.push(tag);
					});
					setAllTags(updatedTags);
				} else console.log(`No tags found on post: ${post.title}`);
			});
		}
	}, [posts]);

	return (
		<>
			<Head>
				<title>Oliver - Blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<section className="px-2 py-3 fixed">
				<FilterChoice
					caption="Filter:"
					choices={allTags}
					activeChoices={activeChoices}
					setActiveChoices={setActiveChoices}
				/>
			</section>
			<h2 className="text-4xl font-bold">Welcome to my blog</h2>
			<p className="text-blue-normal">Please pick a post to get started!</p>
			<ul className="flex flex-col items-center my-4">
				<AnimatePresence>
					{posts &&
						posts.map((content, i) => {
							return activeChoices.length ? (
								Boolean(
									content.tags.some(tag => activeChoices.includes(tag))
								) && <Post key={i} content={content} />
							) : (
								<Post key={i} content={content} />
							);
						})}
				</AnimatePresence>
			</ul>
		</>
	);
};

const client = createClient({
	projectId: "94ov5h9s",
	dataset: "production",
	apiVersion: "2022-05-23",
	useCdn: false,
});

export const getStaticProps = async () => {
	const posts = await client.fetch(`*[_type == "blog-post"]`);

	return {
		props: {
			posts,
		},
	};
};

export default Blog;
