import Head from "next/head";
import Post from "../components/Post";

const posts = [{name: "journey", caption: "Start of my web journey"}];

export default function Blog() {
	return (
		<>
			<Head>
				<title>Oliver Rindholt - Blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h2>Blog</h2>
			<div className="grid grid-cols-2">
				{posts.map((i, {name, caption}) => {
					return <Post key={i} name={name} caption={caption} />;
				})}
			</div>
		</>
	);
}
