import {motion as m} from "framer-motion";
import Head from "next/head";
import Link from "next/link";
import Script from "next/script";
import CareerTree from "../components/CareerTree/Tree";

export default function Home() {
	return (
		<>
			<Head>
				<title>Oliver R. - Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<m.h1
					initial={{x: -100, opacity: 0}}
					animate={{x: 0, opacity: 1}}
					transition={{type: "tween", ease: "easeInOut", duration: 1}}
					className="text-6xl font-light text-left"
				>
					Hi. <span className="font-medium">I'm Oliver.</span>
				</m.h1>
				<m.h2
					className="text-left"
					initial={{x: -100, opacity: 0}}
					animate={{x: 0, opacity: 1}}
					transition={{type: "tween", ease: "easeInOut", duration: 1, delay: 1}}
				>
					Frontend Dev{" "}
					<m.span
						className="!opacity-20"
						initial={{opacity: 0}}
						animate={{opacity: 1}}
						transition={{
							duration: 1,
							delay: 3,
						}}
					>
						(not a designer)
					</m.span>
				</m.h2>
				<CareerTree />
			</div>
		</>
	);
}
