import {formContext} from "../Utility/Context";
import {useContext, useEffect, useState, useRef} from "react";
import {motion as m} from "framer-motion";
import Head from "next/head";
import Link from "next/link";
import CareerTree from "../components/CareerTree/Tree";

const welcomeMessages = [
	"Welcome back",
	"What's up",
	"Good to see you",
	"Hope you're doing well",
	"Thanks for visiting",
	"Greetings",
	"Good, you're back",
];

const capitalizeString = text => {
	if (typeof text === "string" && text.length >= 1) {
		return `${text.charAt(0).toUpperCase()}${text.substring(1)}`;
	} else return null;
};

const randomNum = (min, max) => {
	return Math.floor(Math.random() * (max - min) + min);
};

export default function Home() {
	const {formData} = useContext(formContext);
	const [formSubmitted, setFormSubmitted] = useState(false);
	const [username, setUsername] = useState("");

	useEffect(() => {
		if (Object.keys(formData).length) {
			const {firstName} = formData;
			setFormSubmitted(true);
			setUsername(firstName);
		}
	}, [formData]);

	return (
		<>
			<Head>
				<title>Oliver R. - Home</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<>
				<m.h1
					initial={{x: -20, opacity: 0}}
					animate={{x: 0, opacity: 1}}
					transition={{type: "tween", ease: "easeInOut", duration: 1}}
					className="text-6xl font-light text-left"
				>
					{formSubmitted
						? welcomeMessages[randomNum(0, welcomeMessages.length)] + " "
						: "Hi, "}
					<span className="font-medium">
						{formSubmitted ? capitalizeString(username) : "I'm Oliver"}.
					</span>
				</m.h1>

				<CareerTree />
			</>
		</>
	);
}
